/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Vectors with string-or-int ids, metadata, filtering, and snapshots --
 * same vocabulary as Python's `chronovec.Collection`.
 */
export declare class Collection {
  /**
   * A collection of the given dimensionality with default index options
   * (cosine metric). For custom index options, build a raw `Index` first
   * and wrap it -- not yet exposed through this binding; use the Rust
   * crate directly if you need it today.
   */
  constructor(dimensions: number)
  dimensions(): number
  count(): number
  /** A token for the present, readable later via `query`'s `snapshot` option. */
  snapshot(): bigint
  /**
   * Insert or replace one record.
   *
   * `metadata`/`document` are carried forward from the previous version
   * when omitted (`undefined`) -- matching Python's `Collection.add()`,
   * which carries forward when its `metadatas`/`documents` arguments are
   * omitted entirely. Pass `{}` to explicitly clear metadata to empty
   * (as opposed to omitting it, which keeps whatever it was). There is
   * no way to explicitly clear an existing document back to no document
   * while keeping the metadata -- neither can Python's `Collection.add()`.
   */
  add(id: string | bigint, vector: Float32Array, metadata?: Json | undefined | null, document?: string | undefined | null): bigint
  /**
   * Change an existing record's metadata without touching its vector.
   * Throws if `id` is not currently live.
   */
  updateMetadata(id: string | bigint, metadata: Json): void
  /** Remove one record. Returns whether it was live. */
  delete(id: string | bigint): boolean
  /** Remove every live record matching `where`. Returns their ids. */
  deleteWhere(filter: Json): Array<string | bigint>
  /**
   * Nearest records to `query`, optionally filtered and optionally as of
   * a past snapshot.
   */
  query(query: Float32Array, k: number, options?: QueryJsOptions | undefined | null): Array<Record>
  /** Fetch one live record by id, without a vector search. */
  get(id: string | bigint): Record | null
  /** Fetch every live record matching `where`, without a vector search. */
  getWhere(filter: Json): Array<Record>
  /**
   * Reclaim versions no reader at or after `keepSnapshot` can still
   * reach. Omitted, reclaims everything currently unreachable.
   */
  vacuum(keepSnapshot?: bigint | undefined | null): number
}

/**
 * A snapshot-isolated approximate-nearest-neighbour index.
 *
 * Searches are lock-free over immutable snapshots; mutations are
 * thread-safe but serialise internally, matching the underlying C ABI's own
 * contract -- documented here for completeness, though Node's single
 * JS-thread execution model means it rarely comes up directly the way it
 * would calling this from multiple native threads.
 */
export declare class Index {
  constructor(dimensions: number, options?: IndexOptions | undefined | null)
  dimensions(): number
  /** The current logical clock. `BigInt(clock()) + 1n` sees all committed writes. */
  clock(): bigint
  /** Insert or replace `id`, returning the snapshot at which it became visible. */
  insert(id: bigint, vector: Float32Array): bigint
  /** Delete `id`. Its space is returned by `vacuum`. */
  delete(id: bigint): bigint
  /** The `k` nearest neighbours of `query` in the current state. */
  search(query: Float32Array, k: number): Array<Hit>
  /** The `k` nearest neighbours as the index existed at `snapshot`. */
  searchAsOf(query: Float32Array, k: number, snapshot: bigint): Array<Hit>
  /**
   * Physically reclaim at most `budget` versions no longer visible to any
   * snapshot at or after `oldest`. Bounded: it does not scan the index.
   */
  vacuum(oldest: bigint, budget: number): number
  /** Write a checksummed checkpoint, replacing `path` atomically. */
  save(path: string): void
  /** Restore an index from a checkpoint written by `save`. */
  static load(path: string): Index
  /** Index statistics: live vectors, pages, reclaimed versions, and so on. */
  stats(): Stats
}

/** One search result. */
export interface Hit {
  id: bigint
  distance: number
}

/**
 * Options for [`Index`]. Every field is optional; omitted fields use the
 * same defaults as the Rust crate's own `Index::builder`.
 */
export interface IndexOptions {
  metric?: string
  pageCapacity?: number
  nprobe?: number
  screening?: boolean
  rerankFactor?: number
}

/**
 * Options for [`Collection::query`]. All fields optional; omitted means
 * "now, no filter, default overfetch" -- the equivalent of Python's
 * `col.query(v, k)` with no further keyword arguments.
 */
export interface QueryJsOptions {
  snapshot?: bigint
  where?: Json
  overfetch?: number
}

/** One result from `query`, `get`, or `getWhere`. */
export interface Record {
  id: string | bigint
  distance?: number
  metadata: Json
  document?: string
}

/**
 * Index-wide counters: live vectors, pages, reclaimed versions, and so on.
 *
 * Plain `number`, unlike `id`/snapshot values: these are diagnostic counts
 * (pages, live vectors, reclaimed versions), not values a caller round-trips
 * back into the API, and reaching `Number.MAX_SAFE_INTEGER` here means
 * tens of petabytes of vectors -- not a realistic precision concern.
 */
export interface Stats {
  clock: number
  pages: number
  liveVectors: number
  retainedVersions: number
  allocatedSlots: number
  splits: number
  reclaimedVersions: number
  merges: number
}
